{% set version = "0.2.3" %}

package:
  name: usgs
  version: {{ version }}

source:
  fn: usgs-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/u/usgs/usgs-{{ version }}.tar.gz
  sha256: 1a09dd2d5b65ac83ba81f6f7db3054435b5e92c46f80dd040c363fc238f8b5a1

build:
  number: 0
  skip: True  # [py2k]
  script: python setup.py install --single-version-externally-managed --record record.txt
  preserve_egg_dir: True
  entry_points:
    - usgs=usgs.scripts.cli:usgs

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - click >=4.0
    - requests >=2.7.0
    - requests-futures >=0.9.5

test:
  imports:
    - usgs
    - usgs.scripts
  commands:
    - usgs --help

about:
  home: https://github.com/mapbox/usgs
  license: MIT
  summary: 'Access the USGS inventory service'

extra:
  recipe-maintainers:
    - ocefpaf
