{% set version = "0.2.4" %}

package:
  name: usgs
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/usgs/usgs-{{ version }}.tar.gz
  sha256: df09f07fa7f4345d3a36643c72428ee8351210c56f82b822a11f5be907bc1522

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"
  preserve_egg_dir: True
  entry_points:
    - usgs = usgs.scripts.cli:usgs

requirements:
  build:
    - python >=3
    - pip
  run:
    - python >=3
    - setuptools
    - click >=4.0
    - requests >=2.7.0
    - requests-futures >=0.9.5

test:
  imports:
    - usgs
    - usgs.scripts
  commands:
    - usgs --help

about:
  home: https://github.com/mapbox/usgs
  license: MIT
  summary: 'Access the USGS inventory service'

extra:
  recipe-maintainers:
    - ocefpaf
