travis:
  secure:
    BINSTAR_TOKEN: kpVuqkl+g5ZMfCfFR69FUnsJOZCEPe8ps2EEB4flVqTykCjdQUx1y4qT4UNRl/BgWHwn7H+E8yK3ypymkiOX4K5hNcYoIXHWnPtCG8gNZPK4qsDb2fRvDSjbwT/vVAUjQT1ahI2sZ5sKTiInTtfoX8SKcNs18cZBBsvcdm0thuDOIrnBdCFgxCepYGLOXWWNRY4eox7SxsZ6nYYCWWzd1g2KnmayiursssLkEI2gG1hjYTmy5aCRIyyz6Bc9/wEbeGVBatDHNFSgc19ezlYH4AEAje8CzyT67tRMMzlQTfBOdbFnwWnGu8Qx1JMYQQ1XWUtohrOnpe5BRcNo8i3Y3zp2ShrzjLUrFLGAZTBfpZ3ymHJbEE2ZLe4q82J0A+AK7IbPb3uG8e2CZ2yKdDY8Eo8717YDJnXABls8E6NKPIFolPj60YhwXuBa1ra436ZgIp8vqi1E8ztF6XEA7hcPXif/J7pX+mGSmY6zeO2T66edcb5G77/rhxQPLEJvaHbKh5NM23IDAHIUM3VHvsirZ0hXuIHs+g5kbe5T0OJK1cf5bNEdeD832SVXdddrCzoqgygP1FvFYYYyLf+ddixcYJfiZF4SJ/3YFk9orbWM77AuJdzwjMWrcFczg43E4GrMkamLIDNnIumivUShvk9Sj0Solyz2UE6/IXDkdZdSSCs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
