travis:
  secure:
    BINSTAR_TOKEN: Og6lMSkIZGiIhw5MiJkTq9eBozo6C0R07YXSY5yBV4mRJGzrBTRpkm6q/yX/Gwt+x0HwnupNGLGkBNJgsTGXlShDXX1TpVelgxFbLlrBUEjnY+Gp7N6JTIVsBDVSz2pjRUym+hxK6vQbuvM/m+kMuNjnbTH2SVEeN45bth20BdgR95AQZdwHotBEXwosLddXKPZOCYHrSPYd9d92siiGPG0PxxMJAVa/cHJ6H4jMO3glcnMWUQBeLOze3LqeTkaoqc07naGPyUHvU3Wa0+ZFc+irnmlfd8y4IJOB5KC72N+v+Q3goHTENfWaoW6ERTCn1d5YDcurKfHqlg0mCOnPPVkhdNEgnR/WAde/ugewX2J7+LcVtea2GmCpMVwgDy0EYHU7o44hLND+jJGWF0UgjNLiev9zlDQpwZRdjrQRzKBQP6Bp0Rdt35dP2UaqjLxYVdWk+8ef4N7jFcfstDJL2rLrbTAwyhcJuZrTKMcTEUkqBdZgmTdkyqdkI19otFiWQjC4bLwx1N4BAX706FP1Z3Nqb2wO1GnMZpPx+rOmWYG65rcrSQbAjIeede5zKOeqbXlUz6ksDvBnl6Yaj1e5rN6t5stZHWQid2NF0fsRWLWsHiE5Vbct48TVz7CTISkpLK1kxI52Uonc9rd7RG5CSabsc3OuIkR1RqhOuWFRRtY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
